### ISSUE TITLE
Filwip still fails to build on x86

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FilWip#14]
hrev51173 x86

Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 39, in __init__
    self.run(args)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 402, in run
    self._buildPort(port, True, self.packagesPath)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 622, in _buildPort
    port.patchSource()
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 650, in patchSource
    if source.patch(self):
  File "/boot/home/haikuporter/HaikuPorter/Source.py", line 326, in patch
    sysExit(u'patch file "' + patch + u'" not found.')
  File "/boot/home/haikuporter/HaikuPorter/Utils.py", line 66, in sysExit
    sys.exit(message.encode('utf-8'))
SystemExit: Error: patch file "/boot/home/haikuports/haiku-apps/filwip/patches/filwip-1.0.0.patchset" not found.

**Comment by humdingerb** [comment]
Looks like @korli forgot to add the patchset with https://github.com/haikuports/haikuports/commit/24a28d3ae184e68dd0f4484b33595835c7e2afcd
Or there actually shouldn't be a patchset...

In any case, this is an issue with the haikuporter recipe. FilWip builds here on x86.

**Comment by korli** [comment]
Fixed
